/**
 * Represents an owner
 *
 * @author Chris Loftus
 * @version 23rd February 2021
 */
public class Owner {
    private String name;
    private String phone;

    /**
     * Constructor to build an Owner
     * @param name The owner's name
     * @param phone The owner's phone number
     */
    public Owner(String name, String phone) {
        this.name = name;
        this.phone = phone;
    }

    /**
     * Get the owner's name
     * @return The owner's name
     */
    public String getName() {
        return name;
    }

    /**
     * Set the owners name
     * @param name The owner's name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get the owner's phone number
     * @return The owner's phone number
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Set the owner's phone number
     * @param phone The owner's phone number
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public boolean equals(Object obj) { // Robust version generated by IDE
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Owner other = (Owner) obj;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        if (phone == null) {
            if (other.phone != null)
                return false;
        } else if (!phone.equals(other.phone))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return name + " " + phone;
    }

}
